name: fa
on:
  push:
    branches: [ main ]
    paths:
      - Proxy/**
      - BackgroundService/**
      - .github/workflows/fa.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  # must match resource name in tf
  AZURE_FUNCTION_PROXY: 'weather-api-fa'
  AZURE_FUNCTION_BACKGROUND: 'weather-background-fa'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PROJECT_PATH: 'BackgroundService'

jobs:
  deploy-proxy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions deploy for proxy'
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTION_PROXY }}
        package: './Proxy'

    - name: logout
      run: |
        az logout

  deploy-service:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Dotnet 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: dotnet build and publish
      run: |
        dotnet restore ${{ env.PROJECT_PATH }}
        dotnet build ${{ env.PROJECT_PATH }} --configuration Release
        dotnet publish ${{ env.PROJECT_PATH }} -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/background-service'

    - name: 'Run Azure Functions deploy for background service'
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTION_BACKGROUND }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/background-service'

    - name: logout
      run: |
        az logout
